# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby-augeas/all/ruby-augeas.rbi
#
# ruby-augeas-0.5.0
class Augeas
  def clear(path); end
  def clear_transforms; end
  def clearm(base, sub); end
  def close; end
  def context; end
  def context=(path); end
  def defnode(arg0, arg1, arg2); end
  def defvar(arg0, arg1); end
  def error; end
  def exists(arg0); end
  def get(arg0); end
  def insert(arg0, arg1, arg2); end
  def label(arg0); end
  def load!; end
  def load; end
  def match(arg0); end
  def mv(arg0, arg1); end
  def rename(arg0, arg1); end
  def rm(arg0); end
  def save!; end
  def save; end
  def self.new(*arg0); end
  def self.open(root = nil, loadpath = nil, flags = nil, &block); end
  def self.open3(arg0, arg1, arg2); end
  def set!(path, *values); end
  def set(path, *values); end
  def set_internal(arg0, arg1); end
  def setm(arg0, arg1, arg2); end
  def span(arg0); end
  def srun(arg0); end
  def text_retrieve(arg0, arg1, arg2, arg3); end
  def text_store(arg0, arg1, arg2); end
  def touch(path); end
  def transform(hash); end
end
class Augeas::Error < RuntimeError
end
