# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/yast-rake/all/yast-rake.rbi
#
# yast-rake-0.2.32
module Yast
end
module Yast::Tasks
  def self.configuration(&block); end
  def self.spec_version; end
  def self.submit_to(target, file = nil); end
end
class Yast::SpellcheckTask < Rake::TaskLib
  def block_line?(line); end
  def check_file(file); end
  def colorize?; end
  def config; end
  def files_to_check; end
  def initialize; end
  def inside_block; end
  def misspelled_on_line(text); end
  def print_misspelled(list, index, text); end
  def read_spell_config(file); end
  def report_duplicates(dict1, dict2); end
  def run_task; end
  def speller; end
  def switch_block_tag; end
end
class Object < BasicObject
  def clean_pot_lines(lines); end
  def parallel_rspec_installed?; end
  def parallel_tests_wanted?; end
  def report_pot_errors(lines); end
  def run_parallel_tests(files); end
  def run_rubocop(params = nil); end
  def run_sequential_tests(files); end
  def set_y2dir; end
  def version; end
end
module Packaging
end
class Packaging::Configuration
  def fillup_dir; end
  def install_doc_dir; end
  def install_locations; end
  def install_locations=(arg0); end
end
