# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

Metrics/AbcSize:
  Max: 129
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/AbcSize:
  Max: 30
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/BlockNesting:
  Max: 5
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/BlockNesting:
  Max: 2
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib


# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 385
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 220
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/ModuleLength:
  Max: 385
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/ModuleLength:
  Max: 100
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/CyclomaticComplexity:
  Max: 29
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/CyclomaticComplexity:
  Max: 10
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 299
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 100 # TODO this should be lower for new code
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 160
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'test/**/*.rb'

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 30 # TODO this should be lower for new code
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/PerceivedComplexity:
  Max: 34
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/PerceivedComplexity:
  Max: 10
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

# be more strict then rubocop, 5 is too much
Metrics/ParameterLists:
  Max: 4

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Include:
    - 'src/lib/**/*.rb' # force well documented code only for new code

Naming/FileName:
  Include:
    - 'src/lib/**/*.rb' # force correct names on new code

Style/HashSyntax:
  Include:
    - 'src/lib/**/*.rb' # force new hash style only for new code

# JR: I found lambda easier to read and understand then ->()
Style/Lambda:
  Enabled: false

Naming/MethodName:
  Include:
    - 'src/lib/**/*.rb' # force correct names on new code

Naming/VariableName:
  Include:
    - 'src/lib/**/*.rb' # force known variables only for new code

# alias method is more convenient method for method aliasing
Style/Alias:
  EnforcedStyle: prefer_alias_method

# This two are not equivalent if using refinements (and we use them to add
# functionality to the classes coming from libstorage)
#   using RefinementAddingFooToThing
#   things.map { |s| s.foo } # it works
#   things.map(&:foo) # it does not work
# See https://github.com/bbatsov/rubocop/issues/2720
Style/SymbolProc:
  Enabled: false
