#! /bin/bash
#
# Author: Thorsten Kukuk <kukuk@suse.de>
# (c) 2002 SuSE Linux AG
#

root_dir=$1

sc=$root_dir/boot/silo.conf
sc_tmp=$root_dir/boot/silo.conf.$$

[ -f $sc ] || exit 1

has_message=

grep -q -s 'message' $sc && has_message=1

if [ ! "$has_message" ] ; then
	sed "s|SuSE Linux [0-9].[0-9].* (SPARC)|SuSE Linux 8.1 (SPARC)|" < $root_dir/boot/message > $root_dir/boot/message.YaST2
	mv $root_dir/boot/message.YaST2 $root_dir/boot/message
fi

rm -f $sc_tmp
sed -e 's/vmlinuz.suse/vmlinuz.shipped/' -e 's/initrd.suse/initrd.shipped/' <$sc >$sc_tmp
mv $sc_tmp $sc

