#!/bin/bash
# Compute MILO bootloader on Alpha...
# CD1/milo/boot.conf must be in /tmp/boot.conf

SYSTYPE=`cat /proc/cpuinfo  | grep "system type" | colrm 1 26`
SYSVAR=`cat /proc/cpuinfo  | grep "system variation" | colrm 1 26`

MILO=`cat /tmp/boot.conf | grep "$SYSTYPE:$SYSVAR" | cut -f 3 -d :` 

/bin/cp /usr/lib/$MILO/* /boot
