#!/bin/bash
# Installing aboot bootloader on Alpha...
# needs environment
#  RDEV = <device of />
#  BDEV = <device of /boot>
#

RDSK=`echo $RDEV|tr -d [0-9]`
RDEV_NO=`echo $RDEV|tr -d '[:alpha:]' | tr -d '[=/=]'`

BDEV_NO=`echo $BDEV|tr -d '[:alpha:]' | tr -d '[=/=]'`

/sbin/swriteboot -f3 $RDSK /boot/bootlx
/sbin/abootconf $RDSK $RDEV_NO
rm /etc/aboot.conf
touch /etc/aboot.conf

if [ "$BDEV" != "$RDEV" ]; then
    if [ -n "$KERNEL_22" ]; then
	echo "0:$BDEV_NO/vmlinux.gz ro root=$RDEV" >> /etc/aboot.conf
    fi
    if [ -n "$KERNEL_24" ]; then
	echo "1:$BDEV_NO/vm_24.gz ro root=$RDEV" >> /etc/aboot.conf
    fi
else
    if [ -n "$KERNEL_22" ]; then
	echo "0:$RDEV_NO/boot/vmlinux.gz ro root=$RDEV" >> /etc/aboot.conf
    fi
    if [ -n "$KERNEL_24" ]; then
	echo "1:$RDEV_NO/boot/vm_24.gz ro root=$RDEV" >> /etc/aboot.conf
    fi
fi
echo "_" >> /etc/aboot.conf
