#!/bin/bash
#Update /boot/message to contain help for actual language
#$1 is tmp dir to work in
#$2 is localw in longer form (eg. cs_CZ)
#$3 is locale in shorter form (eg. cs) 
#$4 is directory with sources (usually /etc/bootsplash/themes/SuSE/bootloader)

TMP_DIR=$1;
LOCALE=$2;
LOCALE_SHORT=$3;
SRC_DIR=$4;

cd $TMP_DIR || exit 1;
test -e fgxmenu && rm -rf gfxmenu;
mkdir gfxmenu || exit 2;
cd gfxmenu || exit 3;
/usr/bin/cpio -i < /boot/message || exit 4;
echo $LOCALE >lang || exit 5
test -f $SCR_DIR/texts.$LOCALE && cp $SRC_DIR/texts.$LOCALE . \
 || test -f $SRC_DIR/texts.$LOCALE_SHORT && cp $SRC_DIR/texts.$LOCALE_SHORT .
test -f $SRC_DIR/help.$LOCALE && cp I4/help.$LOCALE . \
 || test -f $SRC_DIR/help.$LOCALE_SHORT && cp $SRC_DIR/help.$LOCALE_SHORT .
ls | cpio -o >/boot/message.new && mv /boot/message.new /boot/message || exit 6
exit 0

